### ISSUE TITLE
include a notion of samples?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#103]
#102 raised the issue of sampling. This is inherently part of simulating a demographic model, so we might consider at least including functions for checking that the sampling is possible for the deme graph (deme ids are in the graph, sampling times are within deme existence times). In addition, forward simulators don't want to simulate unsampled populations (to reduce the computational burden), so we might also consider having some way to prune a deme graph to just the ancestors required to simulate the sample.

**Comment by grahamgower** [comment]
The `prune` feature will probably need @apragsdale's awesome `msprime.DemographyDebugger.possible_lineage_locations()` function that would be imported as part of #86.

**Comment by jeromekelleher** [comment]
All good stuff, thanks @grahamgower. Just to be clear, I don't think we should incorporate sampling into the yaml file format, even when people ask us to (which they probably will). Sampling and demography should be kept separate.

I agree having functions to pull samples from a given DemeGraph would be useful and enable a lot of good functionality (like you mention above).

**Comment by grahamgower** [comment]
Yup, agreed. The yaml format is nice and simple, and we should be very conservative about adding things.

**Comment by apragsdale** [comment]
I think the whole describing samples is nearly entirely separate from describing the demography. Yes, you need to make sure you are sampling from existing demes and that the sampling times make sense, but I think that should be left to the simulators to confirm.

For example, in the `fwdpy11` and `msprime` conversions, sampling never comes up, because it's just defining the `DiscreteDemography` or the population configurations, demographic events, etc, resp. In the `moments` conversion, the sample sizes, sampled demes, and sampling times are inputs of the (to be migrated) `moments.Spectrum.from_demes(DemeGraph)` function, and that function checks for sample consistency and correctness.

So I think we should ignore the issue of sampling altogether, and leave it up to the simulators' implementations to deal with?

**Comment by molpopgen** [comment]
I agree that sampling is a wholly separate concern.  As @apragsdale says, the details depend heavily on the interface conventions of individual software.

**Comment by jeromekelleher** [comment]
Graham does make a good point about the functionality having samples would enable - but maybe this could go as a planned feature for later releases? Nailing down the core data format seems to be the critical thing now, and I think we're all happy that sampling is not part of that.

**Comment by molpopgen** [comment]
Just so that the complexity of this is recorded for the future: taking samples in fwdpy11 is accomplished via any valid callable that accepts 2 arguments (after capturing any other things needed for that callable to work).  This callable is often in pure Python, but it could also be a C++ class make available to Python via pybind11.  This API lets you sample individuals based on any property you can imagine.

[This example](https://fwdpy11.readthedocs.io/en/stable/pages/tutorial.html#recording-ancient-samples-during-a-simulation) from the manual takes samples every 10 generations if they are in the "top half" of fitness and located in the desired deme.

Seems hard to YAML this?

**Comment by grahamgower** [comment]
Haha. Yes, dynamic sampling is not something I'd anticipated!

**Comment by molpopgen** [comment]
I acknowledge that random sampling is probably what most folks imagine most of the time.

> Haha. Yes, dynamic sampling is not something I'd anticipated!

**Comment by grahamgower** [comment]
Closing, because I don't think there's anything actionable here. We're not going to provide any data structures related to sampling.
