### ISSUE TITLE
rename list_demographic_events()

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#170]
The method is classifying the types of ancestor/descendant relationships in the graph (pulse, split, branch, merger, or admix), so it would be nice if it had a name in line with that. Suggestions?

**Comment by apragsdale** [comment]
They're all ancestor/descendant relationships, except for `pulse` events... though it is also an instantaneous/discrete event. Some ideas:

 - `discrete_demographic_events()`, since it lists all discrete mass migration type events but not continuous migration
 - or even just `discrete_events()` for conciseness?
 - `mass_migrations()` - kind of in line with how those event types are specified in msprime or fwdpy11

**Comment by grahamgower** [comment]
Closed by #213.
