### ISSUE TITLE
require deme.start_time and epoch.end_time in input files

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#182]
This change is to follow the reference implementation. See https://github.com/popsim-consortium/demes-spec/issues/32

**Comment by apragsdale** [comment]
My understanding was that the deme does not require a start time, except in scenarios where it has multiple ancestors. Otherwise it inherits the start time from the ancestor's end time, or the start time is set to inf if it has no ancestors. That was what I thought the takeaway of that linked issue was, and how it's implemented in the spec now. Am I wrong about that?

**Comment by grahamgower** [comment]
Yeah, you're right. I opened this issue before looking into the gory details. The essential changes we need to make are to (1) disallow `start_time` in an epoch stanza, (2) allow the omission of `end_time` in the last epoch if the end time is `0`.

I made a start on this in #188. But I won't get back to it for a couple of days because I'll be away from the keyboard (again). So, you're welcome to jump on it and resolve anything that doesn't seem to match the behaviour of the `reference_implementation`.
