### ISSUE TITLE
Epoch.start_time is inconsistent with the spec

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#201]
The spec and reference implementation have done away with the `start_time` property for an epoch. This certainly makes sense for the YAML input, and the data model itself. However, once a YAML file is parsed into a Graph, it's rather useful to be able to inspect the start time of an epoch, without having to look outside the epoch object. Just like the `Deme` class has useful `start_time` and `end_time` properties (as opposed to attributes), so too would it be great to make `Epoch.start_time` a property, rather than an attribute. But if we remove the attribute from the epoch, then it no longer has this information. Should we include a back reference from the Epoch to the Deme it applies to, and use that? Or should we really just remove `Epoch.start_time` and look at the end_time of the previous epoch when we need this info?

**Comment by apragsdale** [comment]
I agree with you Graham that it would be good to be able to grab `Epoch.start_time` directly, even if it isn't explicitly allowed in the specification in the YAML. But if internally, if we ask for `Epoch.start_time` it can just grab the previous epoch's end time or the deme start time if it's the first epoch, maybe that's good enough? I could see that being a bit of a logic pain though. I don't know what the cleanest or most principled way of doing that would be here.

**Comment by jeromekelleher** [comment]
Yes, this is a tricky one - I can see arguments in both directions. Seems to me it's a natural thing to fill out during a ``parse`` operation, where we validate the graph and fill in the implicitly defined information according to the spec. It's not in the spec because it's redundant, but there's nothing stopping us from adding useful additional properties if we like.

However, it should be an error if someone tries to fill it in themselves. Which makes me think we should have a separate graph-building API, rather than composing the actual objects we define...

**Comment by grahamgower** [comment]
> Which makes me think we should have a separate graph-building API, rather than composing the actual objects we define...

I've thought about doing this a couple of times, but the simplcity and elegance of using the API for building has remained very attractive. This works well, excepting some very minor inconsistencies (such as the present issue).

In #188, I've kept `start_time` it in the python `Epoch` class, and it is filled during parsing as you say @jeromekelleher (checking for inconsistencies as usual). It will be an error to specify in the input YAML file once #184 is adressed.

**Comment by grahamgower** [comment]
Closed by #209.
