### ISSUE TITLE
nail down semantics for `size_function`

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#262]
The semantics for `size_function` are not nailed down. See https://github.com/popsim-consortium/demes-spec/issues/34. We're currently allowing any value, but treating "constant" and "exponential" specially (during consistency checks, and during `Graph.asdict_simplified()`). When not specified the defaults are currently:
```python
        if size_function is None:
            if start_size == end_size:
                size_function = "constant"
            else:
                size_function = "exponential"
```
As far as I'm concerned, it would be easiest if we only supported these two options, as then basically all downstream software can do something sensible. But easiest is not necessarily best. Do we want to allow any string here? Do we want to allow other values, such as "linear"? Do we permit downstream software to ignore values it doesn't understand? We currently have a warning in the docs `Warning: Downstream applications might not understand the size_function provided.`, but I find this somewhat unsatisfying --- clearly it would be best if they did.

**Comment by apragsdale** [comment]
> Do we want to allow any string here? Do we want to allow other values, such as "linear"?

I think we want to keep the allowable entries as flexible as possible and not impose any constraints. It's also probably too difficult to guess what the list of allowable strings should be.. ["exponential", "constant", "linear", "logistic", ...] so that we'd be forgetting something that someone might want to allow. So I think allowing any string is appropriate here.

> Do we permit downstream software to ignore values it doesn't understand?

I think we can't control how downstream software use demes, so it's really up to them how they handle the possible size functions (just as with other options such as selfing rate, which not every downstream software will be able to handle)

**Comment by grahamgower** [comment]
> I think we want to keep the allowable entries as flexible as possible and not impose any constraints. It's also probably too difficult to guess what the list of allowable strings should be.. ["exponential", "constant", "linear", "logistic", ...] so that we'd be forgetting something that someone might want to allow. So I think allowing any string is appropriate here.

I think that's essentially what we have now. So we'd want a description in the spec for both "constant" and "exponential", and describe what we do when `size_function` isn't provided but `start_size != end_size` (currently defaults to "exponential"). Right now this forces downstream software to understand both "constant" and "exponential" (which is fine).

> I think we can't control how downstream software use demes, so it's really up to them how they handle the possible size functions (just as with other options such as selfing rate, which not every downstream software will be able to handle)

What's not clear to me is if we're saying "hey simulators, feel free to use this field any way you like". Or, "we're leaving this field here for the possiblity of adding additional well-defined size_function values to the spec in the future" (such as "linear" or "logistic"). I think the former is probably a bad idea, as it could lead to fragmentation in the formats accepted by different tools, when our goal is unification.

**Comment by apragsdale** [comment]
I think it's ok to have it say "feel free to use this field any way you like" as long as we mean any way you'd like to interpolate between `start_size` and `end_size`. There are some software out there that can't handle even exponential size changes, where everything is piecewise constant. And other software where you can give any functions `N(t) = lambda t: whatever` and I think erring on the side of being permissive and allowing whatever flexible function someone wants to write down is the way to go. Luckily this is a corner case and I think most users and software will be quite happy to stick with "constant" and "exponential" (maybe "linear" and "logistic") and I don't foresee fragmentation, but I don't think we want to enforce restricting size functions to that small set.

**Comment by jeromekelleher** [comment]
My take was to leave this field out of the initial specification, since all the downstream software we know about are assuming exponential. I think we could spill a lot of ink debating this back and forth, but until some software is actually using a particular feature it's all a bit pointless.

So, how about we leave it out and just say we assume it's exponential in the spec, and then add it back in when we find some software that needs it?

**Comment by grahamgower** [comment]
> So, how about we leave it out and just say we assume it's exponential in the spec, and then add it back in when we find some software that needs it?

But that won't be backwards-compatible. If we remove `size_function`, then downstream software assumes "exponential" when `start_time != end_time`. So if we later add `size_function` to allow "linear", then downstream software will silently do the wrong thing.

**Comment by grahamgower** [comment]
Ok, I'll do a size_function-ectomy. If we add it back in, then we have to bump the spec version (and add a spec-version field to the data model).

**Comment by molpopgen** [comment]
I agree we can defer this to later.

**Comment by jeromekelleher** [comment]
Sorry, I forgot to follow up on this. What's remaining to be decided for the current size function field? Your point about compatibility is a good one.

(We should add a spec_version field regardless though)

**Comment by grahamgower** [comment]
The alternative to removing `size_function` would be to clarify it's usage in the spec and the docstrings to make explicit statements about which values must be supported and what an implementation should do with values it doesn't understand. Something like the following semantics:

---

The user-provided `size_function` may be any string, or may be omitted. Two special values are recognised: "constant" and "exponential". If the size_function is not specified and `start_size==end_size`, the size_function will be set to "constant". If the size_function is not specified and `start_size!=end_size`, the size_function will be set to "exponential". It is an error to specify `size_function="constant"` when `start_size!=end_size`, but permissible to set `size_function="exponential"` when `start_size==end_size` (although the latter is not recommended). Other values of size_function are permitted, but how these are to be interpreted is deliberately not defined by the spec. The spec may choose to define clear semantics for additional size_function values in the future.

Software that works with the demes data model are required to support the "constant" and "exponential" values for the size_function, and it is recommended that software raises an error for values it does not recognise. E.g. appropriate code for using the demes-python API could look like this:
```python
def size_of_deme_at_time(deme: demes.Deme, time: float) -> float:
    """
    Return the population size of the deme at the given time.
    """
    for epoch in deme.epochs:
        if epoch.start_time >= time >= epoch.end_time:
            break
    else:
        raise ValueError(f"deme {deme.name} doesn't exist at time {time}")

    if epoch.size_function == "constant":
        N = epoch.end_size
    elif epoch.size_function == "exponential":
        dt = (epoch.start_time - time) / epoch.time_span
        r = math.log(epoch.end_size / epoch.start_size)
        N = epoch.start_size * math.exp(r * dt)
    else:
        raise ValueError(f"unrecognised size_function: {epoch.size_function}")
    return N
```

This leaves open the ability to support additional size_function values in the future. The following code is *not* recommended, because it will break in the event that new size_function values are defined in a future version of the spec.

```python
def size_of_deme_at_time(deme: demes.Deme, time: float) -> float:
    """
    Return the population size of the deme at the given time.
    """
    for epoch in deme.epochs:
        if epoch.start_time >= time >= epoch.end_time:
            break
    else:
        raise ValueError(f"deme {deme.name} doesn't exist at time {time}")

    if epoch.start_size == epoch.end_size:
        N = epoch.end_size
    else:
        dt = (epoch.start_time - time) / epoch.time_span
        r = math.log(epoch.end_size / epoch.start_size)
        N = epoch.start_size * math.exp(r * dt)
    return N
```

**Comment by jeromekelleher** [comment]
I think we should say that it must be "constant" or "exponential", with other values optionally added in later versions of the spec, using an explicit enum of accepted values in the spec. If the value is omitted, it's assumed to be "exponential".

I don't think there's much point in having recommendations on setting to "constant" when start_size == end_size, it's just complicating things I think. For example, your code above would have to guard against ``r = 0``, since implementing programs might think they are outputting a non-zero value but it could get rounded to zero during yaml conversion, (e.g.).

Implementations SHOULD check this value to ensure that they support the size function.

That seems straightforward enough to specify then?

That's all we can reasonably do, I think.

**Comment by apragsdale** [comment]
Agree with Jerome here.

> Software that works with the demes data model are required to support the "constant" and "exponential" values for the size_function

Just to note, I think this is too strict of a statement (like saying, if you don't support selfing, you cannot use Demes, which would preclude a lot of software). There are a lot of methods that only deal with piecewise constant demography, so they'd have to check the value of epochs' size functions to make sure that it's a compatible demes models, and otherwise raise an error.

**Comment by grahamgower** [comment]
What does everyone think of #262 then?

**Comment by molpopgen** [comment]
> What does everyone think of #262 then?

Isn't that this?

**Comment by apragsdale** [comment]
> > What does everyone think of #262 then?
> 
> Isn't that this?

#278 I think

**Comment by grahamgower** [comment]
Thanks @apragsdale. It's been a long week...

**Comment by molpopgen** [comment]
I'll try to look this weekend.
