### ISSUE TITLE
deme.size_at(t) returns value when t == start_time

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-python#427]
@molpopgen pointed this out to me last night: We consider deme existence intervals to be half-open, so that `start_time=100` and `end_time=0` means existence over (100, 0]. However, we still get a value returned with `deme.size_at(100)`.

Example:
```python
import demes
b = demes.Builder()
b.add_deme(name="anc", epochs=[dict(end_time=100, start_size=100)])
b.add_deme(name="dec", epochs=[dict(end_time=0, start_size=200)], ancestors=["anc"])
g = b.resolve()
```

and `g["dec"].size_at(100)` returns 200 instead of `ValueError: time 100 is outside deme dec's existence interval: (100, 0]`, as I'd expect.

**Comment by apragsdale** [comment]
It's very possible this is the behavior that we want, but if we say the deme's existence interval is (100, 0], then 100 should be outside of that interval.

**Comment by apragsdale** [comment]
Last comment - I think the `start_time >= time` check instead of `start_time > time` is so that `deme.size_at(np.inf)` is valid, and that makes sense. Just want to double check that this is the behavior we want.

**Comment by molpopgen** [comment]
I do rhink that this is a bug.  The special treatment of Inf is fine, but finite real values should be "not in the interval" when equal to the start time.

**Comment by grahamgower** [comment]
I see your point, but I do think we also want the current behaviour so that `deme.size_at(deme.start_time)` always produces a value. This is completely analogous to looking up `deme.epochs[0].start_size`, which is also technically undefined because it corresponds to the deme's start_time. This makes it reasonable to things like `times = np.linspace(deme.start_time, deme.end_time, 100); sizes = list(map(deme.size_at, times))`.

Is this causing a problem somewhere?

**Comment by apragsdale** [comment]
I don't know if it's causing a problem, but maybe some confusion.

A proposal to get around this might be to not raise an error if the requested time is outside of the interval's existence time, but rather return 0 if outside of that interval? Then asking for `deme.size_at(deme.start_time)` returns 0, and `deme.size_at(deme.start_time - eps)` returns a nonzero number. So in the example about, you'd get

```python
>>> g["dec"].size_at(101)
0
>>> g["dec"].size_at(99)
200
>>> g["dec"].size_at(99.999)
200
>>> g["dec"].size_at(100)
0
```

Thoughts?

**Comment by molpopgen** [comment]
It caused me a problem trying to convert between two different software, which is how I discovered it.  

The current behavior is not consistent with our spec, which states half open intervals.  I read the spec as saying the size is 0 at start_size.  What the function returns is the initial size of a deme whose epoch starts at time x, which is different.  Infinity is a special case, needing special handling.

Related: I also think that it is a bug to raise an error when x is not a time when a deme exists.  I'd prefer None or 0 here.  This is not exceptional in the same way as querying properties of deme IDs that don't exist.  This means I have to do special error handling when cross validating different software.

**Comment by grahamgower** [comment]
Ok, then lets fix this. Do we need to maintain backwards compatiblity here? Returning `0` instead of raising an exception should be ok I guess, as its unlikely anyone would rely on that behaviour. The function came from demesdraw, so I'll have to check if it relies on the behaviour for `deme.size_at(deme.start_time)` (I don't *think* it does). In any event, that would be a potential problem for consuming software, so maybe we need to have a boolean `strict` param for this?

**Comment by jeromekelleher** [comment]
If we define the interval as half-open then we should be strict about it, I think.

I think it's OK to make the breaking change here.
