### ISSUE TITLE
test coverage should be independent of converter tests

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#99]
The `demes.convert.*` functions for msprime/stdpopsim/moments will likely be removed. So we want to ensure our test coverage is not dependent on the tests for these conversion functions. Related to #68.

**Comment by apragsdale** [comment]
I've started working on a larger update release of `moments` that should be ready to go in the next few weeks, and including `demes` support natively within `moments` is on the list of tasks there. So I'm almost ready to remove the moments functions from `demes.convert`, and in any case it will need some updating because the `moments` API is getting streamlined quite a bit.

For `fwdpy11` as well, those conversion functions have been set up and tested elsewhere.

What do you think needs to take place within `stdpopsim` and `msprime` to get the `demes` support within those libraries instead of kept in here?

**Comment by grahamgower** [comment]
Oh, nice! I think we want to have at least a `0.1` release before including `demes` as a dependency anywhere. I'd imagine it won't be an enourmous amount of work to get it into msprime (but we coule easily wait for after msprime 1.0?). It might be more effort in stdpopsim, because there's not much point in doing that without deprecating the current way of defining demographic models (possibly a large task).

**Comment by jeromekelleher** [comment]
Once there's a release of demes, we can easily add the code we have here into the msprime test suite. Once we're ready to make demes a dependency (either in 1.0 or 1.1) we could promote the code to the main library.

**Comment by grahamgower** [comment]
Test coverage is now in pretty good shape. The only thing we're relying on the converter tests for is `Graph.successors`, `Graph.predecessors`, and `Graph.list_demographic_events()`, which are only used in the moments conversion code.

**Comment by apragsdale** [comment]
> The only thing we're relying on the converter tests for is `Graph.successors`, `Graph.predecessors`, and `Graph.list_demographic_events()`, which are only used in the moments conversion code.

We can discuss today in our call, but I think we're ready to remove the `moments` conversion code in `demes`. I've already migrated a lot of it over, getting ready for a `moments` release once `demes` is out and `pip`-installable. I think the only use to keep it for now is as an example for someone else to get some inspiration, like maybe Ryan with `dadi` (but we can always point developers to other repos where its supported).

We still want to keep these `successors`, `predecessors`, etc functions, so we'll want to explicitly test them elsewhere.

**Comment by grahamgower** [comment]
Closed by #213.
